# Generated by Django 4.1.3 on 2023-11-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='BAŞLIK')),
                ('completed', models.BooleanField(verbose_name='DURUM')),
            ],
        ),
    ]
